### ISSUE TITLE
Components are not recognized

### ISSUE THREAD

**Issue by zeljkobajsanski** [GoMarky/vue-shimmer#1]
Hi,
I followed installation instructions but when I am trying to use code from example it doesn't work with vue warning in console
"Unknown custom element: <content-placeholders> - did you register the component correctly? For recursive components, make sure to provide the "name" option." The same is for other components like content-placeholders-heading, content-placeholders-text.
In main.js I registered plugin as explained.

**Comment by TeodorDre** [comment]
Hello! Sorry, it was my mistake. Early project contains incorrect docs. I did it update. You can check it out here - https://github.com/GoMarky/vue-shimmer/blob/master/README.md

Also i add a demo page. In placed here https://github.com/GoMarky/vue-shimmer/tree/master/demo

**Comment by TeodorDre** [comment]
Also, i add possibility for changing colors. Check README.md
